### ISSUE TITLE
filtering by score

### ISSUE THREAD

**Issue by MeHelmy** [infphilo/centrifuge#103]
Hi,
This is not an issue it is an inquiry.
It is suggested in your publication to avoid false positive by filtering score less than 300, meanwhile I did not find any parameter in the centrifuge tool to control that! the way I did it is like that:
`myScore=300;  
centrifuge -f -x test ~/centrifuge/example/reads/input.fa | awk '{if(NR < 2 || $4 >= $myScore) {print}}`

do I miss the parameter that control score! or it is not implemented yet? Is the above code will lead to right results to avoid false positive?

Thanks,
Medhat

**Comment by mourisl** [comment]
The filter by score is not a parameter. Since it is quite easy to filter by the classification result of Centrifuge and people usually want to play around with filter, we decide to leave it as a post-processing choice.
The filter in the manuscript also used the match length and they were for nanopore sequencing reads. You may want to try several different combinations of filters according to your application.

**Comment by MeHelmy** [comment]
Thanks,
Here is what I did . I used different parameters for ` --min-totallen` and ` --min-hitlen`  and filtered the file resulted with -S option (File for classification output) with the minimum score I wanted (for example 300), and I used the `taxID` to get the taxonomy to which this read belongs to.

Is that is logical or there is better way to do it?

Thanks,

**Comment by mourisl** [comment]
Yes, in the current state of Centrifuge, those filters are solid.
