### ISSUE TITLE
refseq_microbial: archaea-chromosome_level is not a valid domain

### ISSUE THREAD

**Issue by sjaenick** [infphilo/centrifuge#35]
The refseq_microbial database target attempts to obtain archaea-chromosome_level and fails:

```
$ make refseq_microbial 
.....
Making: refseq_microbial: refseq_microbial
make -f Makefile IDX_NAME=refseq_microbial
make[1]: Entering directory `/ceph/mgx-sw/src/centrifuge/indices'
[[ -d tmp_refseq_microbial ]] && rm -rf tmp_refseq_microbial; mkdir -p tmp_refseq_microbial
Downloading and dust-masking archaea-chromosome_level
centrifuge-download -o tmp_refseq_microbial  -m -d "archaea-chromosome_level" -P 1 refseq > \
                tmp_refseq_microbial/all-archaea-chromosome_level.map
archaea-chromosome_level is not a valid domain - use one of the following:
make[1]: *** [reference-sequences/all-archaea-chromosome_level.fna] Error 1
make[1]: Leaving directory `/ceph/mgx-sw/src/centrifuge/indices'
make: *** [refseq_microbial] Error 2
$ cat tmp_refseq_microbial/all-archaea-chromosome_level.map 
archaea
bacteria
fungi
invertebrate
plant
protozoa
vertebrate_mammalian
vertebrate_other
viral
$ ls reference-sequences/
all-archaea.fna  all-bacteria.fna  all-fungi.fna  all-protozoa.fna  all-viral.fna
all-archaea.map  all-bacteria.map  all-fungi.map  all-protozoa.map  all-viral.map
```

**Comment by sjaenick** [comment]
I guess the definition for refseq_microbial should be adapted to this:

```
refseq_microbial: export COMPLETE_GENOMES:=archaea bacteria fungi protozoa viral
##refseq_microbial: export CHROMOSOME_LEVEL_GENOMES:=$(COMPLETE_GENOMES)
##refseq_microbial: export SMALL_GENOMES:=mitochondrion plasmid plastid # TODO
##refseq_microbial: export MAMMALIAN_TAXIDS:=9606 10090
##refseq_microbial: export INCLUDE_CONTAMINANTS:=1
refseq_microbial: export IDX_NAME:=refseq_microbial
refseq_microbial: export CF_BUILD_OPTS+=--ftabchars 14
```

**Comment by fbreitwieser** [comment]
It works for me. Are you using the latest GitHub version? Probably its due to different platform / make / bash version. It's really a pain. What's you platform and bash/make versions?

The archaea-chromosome_level.fna should be captured by the following make target:

```
$(REFERENCE_SEQUENCES_DIR)/all-%-chromosome_level.fna: | $(REFERENCE_SEQUENCES_DIR) .dustmasker-ok
   ...
```

The refseq_microbial target downloads all 'Complete' plus all 'Chromosome level' microbial genomes. If you comment the second line, then you only get the complete assemblies.

By the way, you can adjust any of the variables also on the command line. E.g.

`make refseq_microbial MAMMALIAN_TAXIDS="" COMPLETE_GENOMES="archaea bacteria viral" CHROMOSOME_LEVEL_GENOMES=""`

Note that you may want to go into a new directory for index building, and refer to the Makefile with `-f` to avoid interferences with previously partially downloaded files.

**Comment by sjaenick** [comment]
Very strange; it works correctly if I move the all-%-chromosome_level rule in front of the all-%.fna one.

GNU Make 3.81, bash 4.3.11(1)-release on Ubuntu 14.04 LTS.

**Comment by fbreitwieser** [comment]
Hi @sjaenick , please feel free to reopen if the problem still is present.
