### ISSUE TITLE
Questions about NT index generation

### ISSUE THREAD

**Issue by bistace** [infphilo/centrifuge#99]
Hi,
I followed the guidelines available on this page (https://github.com/khyox/recentrifuge/wiki/Centrifuge-nt#download) to generate a NT index.
However, I don't get the same results whether I use the index I generate or the one that you provide here (ftp://ftp.ccb.jhu.edu/pub/infphilo/centrifuge/data/nt_2018_2_12. tar. gz).
Here are the results with the index that I generate myself :

15421 bacterial sequences (77.11%)
200 Eukaryotic sequences (1.00%)
1 virus sequence (0.01%)

And here are the results with the provided index :

15570 Bacterial Sequences (77.85%)
19 Eukaryotic sequences (0.10%)
1 virus sequence (0.01%)

Could you please indicate me how the index you are providing was generated ?

**Comment by mourisl** [comment]
Centrifuge builds the index by downloading the files from NCBI. Since NCBI updates the genomes constantly, it is normal to see different building results. 

But it seems the number of eukaryotic sequences is a bit low in the provided index. I will look into this.

**Comment by mourisl** [comment]
Did you count the number of bacterial and eukaryotic sequences using the taxonomy tree from centrifuge-inspect or from other sources?

**Comment by bistace** [comment]
The results for which I observe 200 eukaryotic sequences (first case) were obtained using an older version of NT from January 2018. To compute the number of bacterial and eukaryotic hits, I parsed the taxids of the class file by using an in-house script.

We sequenced E. Coli so I shouldn't be observing any eukaryotic hits here. Hence I thought my index was generated in a wrong way. That's why I would like to know how you built your index.

**Comment by mourisl** [comment]
I used the default script in the indices folder "make THREADS=10 nt".

Is the "number of sequences" the number of of sequence read from the FASTQ file you sequenced or the number of sequence in the index file?
If it is the sequence reads, I think the result is reasonable. Because the assignment to the eucaryotic genomes are false positive they should have a low score. Some changes in the reference database could create a better hit for that read thus it won't be assigned to eucaryotic genomes.

**Comment by khyox** [comment]
Hi,

The guidelines at [Centrifuge-nt](https://github.com/khyox/recentrifuge/wiki/Centrifuge-nt) are  basic instructions for a _manual_ build of the Centrifuge **nt** database. The main differences with the automatic process provided by the index `Makefile` (ftp://ftp.ccb.jhu.edu/pub/infphilo/centrifuge/downloads/centrifuge-1.0.3-beta/indices/Makefile) are:

1. Both methods use `nucl_gb.accession2taxid.gz` and `nucl_wgs.accession2taxid.gz` from NCBI accession2taxid (ftp://ftp.ncbi.nih.gov/pub/taxonomy/accession2taxid/). The instructions at [Centrifuge-nt](https://github.com/khyox/recentrifuge/wiki/Centrifuge-nt) are more general in the accession to taxid mapping, in the sense that they also use `nucl_est.accession2taxid.gz`, `nucl_gss.accession2taxid.gz` and `prot.accession2taxid.gz` since I found them useful in some cases.
2. The index `Makefile` calls `centrifuge-sort-nt.pl` to generate the conversion table used by `centrifuge-build`, which also sorts the nt fasta file.
3. The `Makefile` is performing and additional step for masking low-complexity sequences by using [dustmasker](https://www.liebertpub.com/doi/pdf/10.1089/cmb.2006.13.1028), a BLAST command-line application. The index `Makefile`, it calls `dustmasker` with the DUST level (score threshold for subwindows) set to 20, which is the default. Finally, all the masked nucleotides by `dustmasker` are remasked as `N` (using `sed '/^>/! s/[^AGCT]/N/g'`). This step can be skipped passing the parameter `DONT_DUSTMASK=1` to the `make` command but, by default, the masking is done.

I think that the differences in the Eukaryotic sequences that you observe could be explained by these differences between both methods, especially the last one. As Li has commented, since the assignments to the eukaryotic genomes are false positives, they should have a low score. Filtering by score should solve this issue. You can increase the minimum hit length (mhl) parameter for Centrifuge. Alternatively, you can simply use [Recentrifuge](https://github.com/khyox/recentrifuge) to filter by any desired score level (over the mhl you gave to Centrifuge) using the flag `--minscore`.

I personally run Centrifuge with a base mhl of 20 and then I get quickly different results filtered with Recentrifuge for higher values, depending on the nature of the original dataset.

**Comment by bistace** [comment]
Hi,
thanks for all these information, I should be good to go now!
